name: ci

on:
  push:
    branches: [master]
    tags: [v*]
  pull_request:
    branches: [master]

jobs:
  matrix:
    strategy:
      matrix:
        go-version: [^1.*, 1.18.x, 1.16.x, 1.13.x]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - uses: actions/checkout@v3
      - run: go get -v -t -d ./...
      - run: go test -v ./...
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Coverage on latest 1.x Go
        uses: actions/setup-go@v3
        with:
          go-version: ^1.*
      - uses: actions/checkout@v3
      - run: go get -v -t -d ./...
      - run: go test -v -coverprofile=coverage.out -covermode=count ./...
      - uses: codecov/codecov-action@v3
        with:
          files: ./coverage.out
          fail_ci_if_error: true
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: ^1.*
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
